# Use the official Python image
FROM python:3.10

# Set working directory
WORKDIR /app

# Copy all contents into the image
COPY . .

# Install dependencies
RUN pip install pandas matplotlib scipy jupyter nbconvert

# Convert the notebook to HTML when the container runs
CMD ["jupyter", "nbconvert", "--to", "html", "HomeworkOne.ipynb"]
